# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookie_app', '0029_auto_20150130_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInitial_Borr_List_Page',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('AtoZ_ID', models.CharField(default='0000000', max_length=150, null=True, verbose_name='id')),
                ('BankName', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Lender Name')),
                ('Business_Name', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Company Name')),
                ('checkins', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Facebook Checkins')),
                ('Est_Rent_Annual_Expense', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Estimated Rent')),
                ('executivedetails', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Executive Name')),
                ('final_phone', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Validated Phone')),
                ('first_loan_date', models.CharField(default='0000000', max_length=150, null=True, verbose_name='First Loan Date')),
                ('Franchise', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Franchise')),
                ('InitialInterestRate', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Interest Rate')),
                ('last_loan_date', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Last Loan Date')),
                ('last_loan_end', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Last Loan End')),
                ('likes', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Facebook Likes')),
                ('link', models.URLField(default='0000000', max_length=150, null=True, verbose_name='Facebook Link')),
                ('final_employees', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Employees (est.)')),
                ('Main_Line_of_Business', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Industry')),
                ('Manufacturer', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Manufacturer')),
                ('NaicsDescription', models.CharField(default='0000000', max_length=150, null=True, verbose_name='NAICS Description')),
                ('num_loans', models.CharField(default='0000000', max_length=150, null=True, verbose_name='SBA Loans (2007+)')),
                ('ownsrentsindicator', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Own/Rent')),
                ('Physical_City', models.CharField(default='0000000', max_length=150, null=True, verbose_name='City')),
                ('Physical_State', models.CharField(default='0000000', max_length=150, null=True, verbose_name='State')),
                ('Physical_ZIP', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Zip')),
                ('rating', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Yelp Rating')),
                ('Revenue_Yr', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Revenue (est.)')),
                ('review_count', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Yelp Review Count')),
                ('Square_Footage', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Square Footage')),
                ('street3', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Address')),
                ('sum_loans', models.CharField(default='0000000', max_length=150, null=True, verbose_name='SBA Loan vol. (2007+)')),
                ('Website', models.URLField(default='0000000', max_length=150, null=True, verbose_name='Website')),
                ('X2013_Employees', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Employees (2013 est.)')),
                ('X2013_Revenue_Yr', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Revenue (2013 est.)')),
                ('final_yr_incorporated', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Year of Incorporation')),
                ('url', models.URLField(default='0000000', max_length=150, null=True, verbose_name='Yelp Link')),
                ('centile', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Loan Likelihood Score')),
                ('Created_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('FindMoreData', models.BooleanField(default=False, verbose_name='Find More Information')),
                ('FollowUp', models.BooleanField(default=False, verbose_name='Contact Business')),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical initial_ borr_ list_ page',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='HistoricalMore_Data_Page',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('FindMoreData', models.BooleanField(default=False, verbose_name='Find More Information')),
                ('FollowUp', models.BooleanField(default=False, verbose_name='Contact Business')),
                ('AtoZ_ID', models.CharField(default='0000000', max_length=150, null=True, verbose_name='id')),
                ('BankName', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Lender Name')),
                ('Business_Name', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Company Name')),
                ('checkins', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Facebook Checkins')),
                ('Est_Rent_Annual_Expense', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Estimated Rent')),
                ('executivedetails', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Executive Name')),
                ('final_phone', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Validated Phone')),
                ('first_loan_date', models.CharField(default='0000000', max_length=150, null=True, verbose_name='First Loan Date')),
                ('Franchise', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Franchise')),
                ('InitialInterestRate', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Interest Rate')),
                ('last_loan_date', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Last Loan Date')),
                ('last_loan_end', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Last Loan End')),
                ('likes', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Facebook Likes')),
                ('link', models.URLField(default='0000000', max_length=150, null=True, verbose_name='Facebook Link')),
                ('final_employees', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Employees (est.)')),
                ('Main_Line_of_Business', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Industry')),
                ('Manufacturer', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Manufacturer')),
                ('NaicsDescription', models.CharField(default='0000000', max_length=150, null=True, verbose_name='NAICS Description')),
                ('num_loans', models.CharField(default='0000000', max_length=150, null=True, verbose_name='SBA Loans (2007+)')),
                ('ownsrentsindicator', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Own/Rent')),
                ('Physical_City', models.CharField(default='0000000', max_length=150, null=True, verbose_name='City')),
                ('Physical_State', models.CharField(default='0000000', max_length=150, null=True, verbose_name='State')),
                ('Physical_ZIP', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Zip')),
                ('rating', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Yelp Rating')),
                ('Revenue_Yr', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Revenue (est.)')),
                ('review_count', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Yelp Review Count')),
                ('Square_Footage', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Square Footage')),
                ('street3', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Address')),
                ('sum_loans', models.CharField(default='0000000', max_length=150, null=True, verbose_name='SBA Loan vol. (2007+)')),
                ('Website', models.URLField(default='0000000', max_length=150, null=True, verbose_name='Website')),
                ('X2013_Employees', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Employees (2013 est.)')),
                ('X2013_Revenue_Yr', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Revenue (2013 est.)')),
                ('final_yr_incorporated', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Year of Incorporation')),
                ('url', models.URLField(default='0000000', max_length=150, null=True, verbose_name='Yelp Link')),
                ('centile', models.CharField(default='0000000', max_length=150, null=True, verbose_name='Loan Likelihood Score')),
                ('Created_id', models.IntegerField(db_index=True, null=True, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical more_ data_ page',
            },
            bases=(models.Model,),
        ),
    ]
